[package]
name = "bacnet"
version = "0.1.0"
edition = "2021"

[dependencies]
bacnet-sys = { path = "../bacnet-sys" }
once_cell = "1"
log = "0"
thiserror = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
pretty_env_logger = "0"
structopt = "0"
